IC_PATTERNS = ["INSURANCE", "POLICY", "VEHICLE ID NUMBER", "EXPIRATION DATE"]
DRIVING_PATTERN = ["DRIVING", "LICENSE", "DRIVER", "DLN", "EXP"]
PASSPORT_PATTERNS = ["PASSPORT", "ISSUED", "SEX", "EXPIRES", "ISSUES"]

IC_NUMBER_REGREX = "^[0-9]{11}$"
DRIVING_IC_NUMBER_REGREX = "^\\d\\d\\d\\d\\d\\d\\d\\d\\d\\d\\d\\d$"

PASSPORT_DATE_REGREX = "\\d\\d\\s(?:JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)\\s\\d{2}"
DRIVING_DATE_REGREX = "^(0?[1-9]|[12][0-9]|3[01])/(0?[1-9]|1[0-2])/\\d\\d\\d\\d$"
